# Generated by Django 3.0.8 on 2020-07-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('vegan_pizza_type', models.CharField(max_length=200)),
                ('menu_description', models.TextField(blank=True)),
                ('facebook_page', models.URLField()),
                ('pizza_photo', models.ImageField(blank=True, upload_to='images/')),
                ('is_subscriber', models.BooleanField(default=False, help_text='Indicates whether this pizzeria subscribes to PMQ Magazine', verbose_name='Subscribes to PMQ?')),
            ],
        ),
    ]
