# Generated by Django 3.0.8 on 2020-07-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200730_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
