# Generated by Django 3.0.8 on 2020-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook_page',
            field=models.TextField(max_length=200),
        ),
    ]
