# Generated by Django 3.0.8 on 2020-09-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_surveyresponse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='TapTheTableResponse',
        ),
    ]
