# Generated by Django 3.0.8 on 2020-09-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20200921_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapthetableresponse',
            name='online_ordering_link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tapthetableresponse',
            name='facebook_page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
