# Generated by Django 3.0.8 on 2020-09-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='Draft', max_length=50),
        ),
    ]
